didemo:
  jms:
    username: diloginjms
    password: dipassjms
    url: localhost:8090

---
spring:
  profiles: de
didemo:
  jms:
    username: germanJMSUser
    password: germanJMSPass
    url: localhost:9473